#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Dec 24, 2017 09:45:15 PM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import sctl_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Synth_Control (root)
    sctl_support.init(root, top)
    root.mainloop()
    sctl_support.stop_synth()

w = None
def create_Synth_Control(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Synth_Control (w)
    sctl_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Synth_Control():
    global w
    w.destroy()
    w = None


class Synth_Control:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 

        top.geometry("586x343+404+124")
        top.title("Synth Control")
        top.configure(relief="raised")
        top.configure(highlightcolor="black")
        top.bind('<Key>',lambda e:sctl_support.kbd_event(e))



        self.Button1 = Button(top)
        self.Button1.place(relx=0.07, rely=0.15, height=56, width=67)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(command=sctl_support.drum1)
        self.Button1.configure(text='''1''')

        self.Button2 = Button(top)
        self.Button2.place(relx=0.27, rely=0.15, height=56, width=67)
        self.Button2.configure(activebackground="#d9d9d9")
        self.Button2.configure(command=sctl_support.drum2)
        self.Button2.configure(text='''2''')

        self.Button3 = Button(top)
        self.Button3.place(relx=0.48, rely=0.15, height=56, width=67)
        self.Button3.configure(activebackground="#d9d9d9")
        self.Button3.configure(command=sctl_support.drum3)
        self.Button3.configure(text='''3''')

        self.Button4 = Button(top)
        self.Button4.place(relx=0.68, rely=0.15, height=56, width=67)
        self.Button4.configure(activebackground="#d9d9d9")
        self.Button4.configure(command=sctl_support.drum4)
        self.Button4.configure(text='''4''')

        self.but46 = Button(top)
        self.but46.place(relx=0.19, rely=0.15, height=24, width=24)
        self.but46.configure(activebackground="#d9d9d9")
        self.but46.configure(command=sctl_support.d1u)
        self._img1 = PhotoImage(file="./images/up.gif")
        self.but46.configure(image=self._img1)
        self.but46.configure(width=26)

        self.Button10 = Button(top)
        self.Button10.place(relx=0.19, rely=0.23, height=24, width=24)
        self.Button10.configure(activebackground="#d9d9d9")
        self.Button10.configure(command=sctl_support.d1d)
        self._img2 = PhotoImage(file="./images/down.gif")
        self.Button10.configure(image=self._img2)
        self.Button10.configure(width=24)

        self.Button11 = Button(top)
        self.Button11.place(relx=0.39, rely=0.15, height=24, width=24)
        self.Button11.configure(activebackground="#d9d9d9")
        self.Button11.configure(command=sctl_support.d2u)
        self._img3 = PhotoImage(file="./images/up.gif")
        self.Button11.configure(image=self._img3)
        self.Button11.configure(width=26)

        self.Button12 = Button(top)
        self.Button12.place(relx=0.39, rely=0.23, height=24, width=24)
        self.Button12.configure(activebackground="#d9d9d9")
        self.Button12.configure(command=sctl_support.d2d)
        self._img4 = PhotoImage(file="./images/down.gif")
        self.Button12.configure(image=self._img4)
        self.Button12.configure(width=24)

        self.Button13 = Button(top)
        self.Button13.place(relx=0.6, rely=0.15, height=24, width=24)
        self.Button13.configure(activebackground="#d9d9d9")
        self.Button13.configure(command=sctl_support.d3u)
        self._img5 = PhotoImage(file="./images/up.gif")
        self.Button13.configure(image=self._img5)
        self.Button13.configure(width=26)

        self.Button14 = Button(top)
        self.Button14.place(relx=0.8, rely=0.15, height=24, width=24)
        self.Button14.configure(activebackground="#d9d9d9")
        self.Button14.configure(command=sctl_support.d4u)
        self._img6 = PhotoImage(file="./images/up.gif")
        self.Button14.configure(image=self._img6)
        self.Button14.configure(width=26)

        self.Button15 = Button(top)
        self.Button15.place(relx=0.6, rely=0.23, height=24, width=24)
        self.Button15.configure(activebackground="#d9d9d9")
        self.Button15.configure(command=sctl_support.d3d)
        self._img7 = PhotoImage(file="./images/down.gif")
        self.Button15.configure(image=self._img7)
        self.Button15.configure(width=24)

        self.Button16 = Button(top)
        self.Button16.place(relx=0.8, rely=0.23, height=24, width=24)
        self.Button16.configure(activebackground="#d9d9d9")
        self.Button16.configure(command=sctl_support.d4d)
        self._img8 = PhotoImage(file="./images/down.gif")
        self.Button16.configure(image=self._img8)
        self.Button16.configure(width=24)

        self.Label1 = Label(top)
        self.Label1.place(relx=0.07, rely=0.73, height=28, width=206)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(relief=SUNKEN)

        self.Button5 = Button(top)
        self.Button5.place(relx=0.07, rely=0.82, height=24, width=94)
        self.Button5.configure(activebackground="#d9d9d9")
        self.Button5.configure(command=sctl_support.s_up)
        self._img9 = PhotoImage(file="./images/down.gif")
        self.Button5.configure(image=self._img9)

        self.Button6 = Button(top)
        self.Button6.place(relx=0.24, rely=0.82, height=24, width=104)
        self.Button6.configure(activebackground="#d9d9d9")
        self.Button6.configure(command=sctl_support.s_dn)
        self._img10 = PhotoImage(file="./images/up.gif")
        self.Button6.configure(image=self._img10)

        self.Button7 = Button(top)
        self.Button7.place(relx=0.07, rely=0.41, height=56, width=67)
        self.Button7.configure(activebackground="#d9d9d9")
        self.Button7.configure(command=sctl_support.drum5)
        self.Button7.configure(text='''5''')

        self.Button8 = Button(top)
        self.Button8.place(relx=0.27, rely=0.41, height=56, width=67)
        self.Button8.configure(activebackground="#d9d9d9")
        self.Button8.configure(command=sctl_support.drum6)
        self.Button8.configure(text='''6''')

        self.Button9 = Button(top)
        self.Button9.place(relx=0.48, rely=0.41, height=56, width=67)
        self.Button9.configure(activebackground="#d9d9d9")
        self.Button9.configure(command=sctl_support.drum7)
        self.Button9.configure(text='''7''')

        self.Button17 = Button(top)
        self.Button17.place(relx=0.68, rely=0.41, height=56, width=67)
        self.Button17.configure(activebackground="#d9d9d9")
        self.Button17.configure(command=sctl_support.drum8)
        self.Button17.configure(text='''8''')

        self.cpd44 = Button(top)
        self.cpd44.place(relx=0.19, rely=0.41, height=24, width=24)
        self.cpd44.configure(activebackground="#d9d9d9")
        self.cpd44.configure(command=sctl_support.d5u)
        self._img11 = PhotoImage(file="./images/up.gif")
        self.cpd44.configure(image=self._img11)
        self.cpd44.configure(width=26)

        self.cpd45 = Button(top)
        self.cpd45.place(relx=0.19, rely=0.5, height=24, width=24)
        self.cpd45.configure(activebackground="#d9d9d9")
        self.cpd45.configure(command=sctl_support.d5d)
        self._img12 = PhotoImage(file="./images/down.gif")
        self.cpd45.configure(image=self._img12)
        self.cpd45.configure(width=26)

        self.cpd46 = Button(top)
        self.cpd46.place(relx=0.39, rely=0.41, height=24, width=24)
        self.cpd46.configure(activebackground="#d9d9d9")
        self.cpd46.configure(command=sctl_support.d6u)
        self._img13 = PhotoImage(file="./images/up.gif")
        self.cpd46.configure(image=self._img13)
        self.cpd46.configure(width=26)

        self.cpd54 = Button(top)
        self.cpd54.place(relx=0.6, rely=0.41, height=24, width=24)
        self.cpd54.configure(activebackground="#d9d9d9")
        self.cpd54.configure(command=sctl_support.d7u)
        self._img14 = PhotoImage(file="./images/up.gif")
        self.cpd54.configure(image=self._img14)
        self.cpd54.configure(width=26)

        self.cpd55 = Button(top)
        self.cpd55.place(relx=0.8, rely=0.41, height=24, width=24)
        self.cpd55.configure(activebackground="#d9d9d9")
        self.cpd55.configure(command=sctl_support.d8u)
        self._img15 = PhotoImage(file="./images/up.gif")
        self.cpd55.configure(image=self._img15)
        self.cpd55.configure(width=26)

        self.cpd56 = Button(top)
        self.cpd56.place(relx=0.39, rely=0.5, height=24, width=24)
        self.cpd56.configure(activebackground="#d9d9d9")
        self.cpd56.configure(command=sctl_support.d6d)
        self._img16 = PhotoImage(file="./images/down.gif")
        self.cpd56.configure(image=self._img16)
        self.cpd56.configure(width=26)

        self.cpd57 = Button(top)
        self.cpd57.place(relx=0.6, rely=0.5, height=24, width=24)
        self.cpd57.configure(activebackground="#d9d9d9")
        self.cpd57.configure(command=sctl_support.d7d)
        self._img17 = PhotoImage(file="./images/down.gif")
        self.cpd57.configure(image=self._img17)
        self.cpd57.configure(width=26)

        self.cpd58 = Button(top)
        self.cpd58.place(relx=0.8, rely=0.5, height=24, width=24)
        self.cpd58.configure(activebackground="#d9d9d9")
        self.cpd58.configure(command=sctl_support.d8d)
        self._img18 = PhotoImage(file="./images/down.gif")
        self.cpd58.configure(image=self._img18)
        self.cpd58.configure(width=26)






if __name__ == '__main__':
    import os
    os.chdir(os.path.dirname(os.path.realpath(__file__)))
    vp_start_gui()



